server:
  port: 8080
dubbo:
  application:
    id: first-dubbo-provider
    name: first-dubbo-provider

  protocol:
    id: dubbo
    name: dubbo
    port: 27017
  registry:
    id: first-registry
    address: zookeeper://192.168.99.100:2181
  scan:
    base-packages: com.dante.spring.dubbo.impl