server:
  port: 8081
dubbo:
  application:
    id: first-dubbo-consumer
    name: first-dubbo-consumer

  protocol:
    id: dubbo
    name: dubbo
    port: 27017
  registry:
    address: zookeeper://192.168.99.100:2181